# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.57782742 0.30001943 0.70137804 0.53368726 0.72527046]
 [0.2052008  0.24919385 0.65780589 0.71333827 0.51569658]
 [0.70483947 0.73413037 0.4718543  0.0667752  0.72725682]
 [0.95471388 0.40050119 0.19004815 0.60244919 0.86427857]
 [0.60667828 0.40264779 0.59155183 0.09964067 0.60965519]]

[[-0.91384315  0.71464905 -0.66904594 -1.45098513  0.10294989]
 [-0.72417378  1.03150963 -0.68357776 -0.62282788 -0.77005685]
 [-0.55885965  0.35597583  0.72653147  1.33109256  0.34967987]
 [ 0.28088781  1.3187404   0.97707931 -0.04063222 -0.56628363]
 [ 0.18043812 -0.43037738  0.55068917  0.21231453 -0.22030748]
 [-0.92784759 -1.76360256 -1.27605655  0.05603157  0.03402691]
 [-0.59542864 -0.23772241  0.14644762 -0.375385    0.80206523]
 [-0.08660808  0.5079129  -0.02411295 -1.61028106 -0.93392033]
 [-1.40044273  1.48423748 -1.00535968  1.24714024 -1.22361144]
 [ 1.20119519 -0.80710214  1.56808026 -1.82262062 -0.83680709]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5282575568324447
0.8919266970640195


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.06677520472532039
1.5680802631500947


In [14]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 1.67450535  0.93316653  0.08292095 -0.54068088  1.67461019 -0.4835272
 -0.38912771  0.38532134  0.73045777  0.71260902 -1.34951902 -0.40830345
  1.62102     0.00950927  0.95729181 -0.44704279  1.39532733 -0.87862938
  0.53395232]
-0.3891277089113464


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 1.67461019 -0.4835272  -0.38912771  0.38532134  0.73045777]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 1.67450535 -0.54068088 -0.38912771  0.71260902  1.62102   ]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.57782742 0.30001943 0.70137804 0.53368726 0.72527046]
 [0.2052008  0.24919385 0.65780589 0.71333827 0.51569658]
 [0.70483947 0.73413037 0.4718543  0.0667752  0.72725682]
 [0.95471388 0.40050119 0.19004815 0.60244919 0.86427857]
 [0.60667828 0.40264779 0.59155183 0.09964067 0.60965519]]
0.65780589255438
0.65780589255438


In [19]:
print(rand_mat[0:2,1:3])

[[0.30001943 0.70137804]
 [0.24919385 0.65780589]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 1.67450535  0.93316653  0.08292095 -0.54068088  1.67461019 -0.4835272
 -0.38912771  0.38532134  0.73045777  0.71260902 -1.34951902 -0.40830345
  1.62102     0.00950927  0.95729181 -0.44704279  1.39532733 -0.87862938
  0.53395232]

[ 1.67450535  0.93316653  0.08292095  4.          4.         -0.4835272
 -0.38912771  0.38532134  0.73045777  0.71260902 -1.34951902 -0.40830345
  1.62102     0.00950927  0.95729181 -0.44704279  1.39532733 -0.87862938
  0.53395232]

[ 1.67450535  0.93316653  0.08292095  1.          2.         -0.4835272
 -0.38912771  0.38532134  0.73045777  0.71260902 -1.34951902 -0.40830345
  1.62102     0.00950927  0.95729181 -0.44704279  1.39532733 -0.87862938
  0.53395232]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.57782742 0.30001943 0.70137804 0.53368726 0.72527046]
 [0.2052008  0.24919385 0.65780589 0.71333827 0.51569658]
 [0.70483947 0.73413037 0.4718543  0.0667752  0.72725682]
 [0.95471388 0.40050119 0.19004815 0.60244919 0.86427857]
 [0.60667828 0.40264779 0.59155183 0.09964067 0.60965519]]

[[0.57782742 0.30001943 0.70137804 0.53368726 0.72527046]
 [0.2052008  0.24919385 0.65780589 0.         0.        ]
 [0.70483947 0.73413037 0.4718543  0.         0.        ]
 [0.95471388 0.40050119 0.19004815 0.60244919 0.86427857]
 [0.60667828 0.40264779 0.59155183 0.09964067 0.60965519]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.57782742 0.30001943 0.70137804]
 [0.2052008  0.24919385 0.65780589]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.53368726 0.72527046]
 [3.         3.         3.         0.         0.        ]
 [0.70483947 0.73413037 0.4718543  0.         0.        ]
 [0.95471388 0.40050119 0.19004815 0.60244919 0.86427857]
 [0.60667828 0.40264779 0.59155183 0.09964067 0.60965519]]


In [24]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.53368726 0.72527046]
 [3.         3.         3.         0.         0.        ]
 [0.70483947 0.73413037 0.4718543  0.         0.        ]
 [0.95471388 0.40050119 0.19004815 0.60244919 0.86427857]
 [0.60667828 0.40264779 0.59155183 0.09964067 0.60965519]]


In [25]:
# break here for next video

In [26]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 1.61500101  0.23029865  0.19011585  0.95100514 -0.15056233 -0.48576598
 -0.60287678  1.3239548  -0.26805256  0.12618843  0.76671695 -0.98228993
 -0.84291822  0.63087481 -2.01296723]
[ True  True  True  True False False False  True False  True  True False
 False  True False]
[1.61500101 0.23029865 0.19011585 0.95100514 1.3239548  0.12618843
 0.76671695 0.63087481]


In [27]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.91384315  0.71464905 -0.66904594 -1.45098513  0.10294989]
 [-0.72417378  1.03150963 -0.68357776 -0.62282788 -0.77005685]
 [-0.55885965  0.35597583  0.72653147  1.33109256  0.34967987]
 [ 0.28088781  1.3187404   0.97707931 -0.04063222 -0.56628363]
 [ 0.18043812 -0.43037738  0.55068917  0.21231453 -0.22030748]
 [-0.92784759 -1.76360256 -1.27605655  0.05603157  0.03402691]
 [-0.59542864 -0.23772241  0.14644762 -0.375385    0.80206523]
 [-0.08660808  0.5079129  -0.02411295 -1.61028106 -0.93392033]
 [-1.40044273  1.48423748 -1.00535968  1.24714024 -1.22361144]
 [ 1.20119519 -0.80710214  1.56808026 -1.82262062 -0.83680709]]
[0.71464905 0.10294989 1.03150963 0.35597583 0.72653147 1.33109256
 0.34967987 0.28088781 1.3187404  0.97707931 0.18043812 0.55068917
 0.21231453 0.05603157 0.03402691 0.14644762 0.80206523 0.5079129
 1.48423748 1.24714024 1.20119519 1.56808026]


In [28]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 1.61500101  0.23029865  0.19011585  0.95100514 -0.15056233 -0.48576598
 -0.60287678  1.3239548  -0.26805256  0.12618843  0.76671695 -0.98228993
 -0.84291822  0.63087481 -2.01296723]

[-5.          0.23029865  0.19011585 -5.         -0.15056233 -0.48576598
 -0.60287678 -5.         -0.26805256  0.12618843 -5.         -0.98228993
 -0.84291822 -5.         -2.01296723]


In [29]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [30]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [31]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.91384315  0.71464905 -0.66904594 -1.45098513  0.10294989]
 [-0.72417378  1.03150963 -0.68357776 -0.62282788 -0.77005685]
 [-0.55885965  0.35597583  0.72653147  1.33109256  0.34967987]
 [ 0.28088781  1.3187404   0.97707931 -0.04063222 -0.56628363]
 [ 0.18043812 -0.43037738  0.55068917  0.21231453 -0.22030748]
 [-0.92784759 -1.76360256 -1.27605655  0.05603157  0.03402691]
 [-0.59542864 -0.23772241  0.14644762 -0.375385    0.80206523]
 [-0.08660808  0.5079129  -0.02411295 -1.61028106 -0.93392033]
 [-1.40044273  1.48423748 -1.00535968  1.24714024 -1.22361144]
 [ 1.20119519 -0.80710214  1.56808026 -1.82262062 -0.83680709]]



In [32]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.53368726 0.72527046]
 [3.         3.         3.         0.         0.        ]
 [0.70483947 0.73413037 0.4718543  0.         0.        ]
 [0.95471388 0.40050119 0.19004815 0.60244919 0.86427857]
 [0.60667828 0.40264779 0.59155183 0.09964067 0.60965519]]

[[-0.91384315  0.71464905 -0.66904594 -1.45098513  0.10294989]
 [-0.72417378  1.03150963 -0.68357776 -0.62282788 -0.77005685]
 [-0.55885965  0.35597583  0.72653147  1.33109256  0.34967987]
 [ 0.28088781  1.3187404   0.97707931 -0.04063222 -0.56628363]
 [ 0.18043812 -0.43037738  0.55068917  0.21231453 -0.22030748]
 [-0.92784759 -1.76360256 -1.27605655  0.05603157  0.03402691]
 [-0.59542864 -0.23772241  0.14644762 -0.375385    0.80206523]
 [-0.08660808  0.5079129  -0.02411295 -1.61028106 -0.93392033]
 [-1.40044273  1.48423748 -1.00535968  1.24714024 -1.22361144]
 [ 1.20119519 -0.80710214  1.56808026 -1.82262062 -0.83680709]]
[[3.         3.         3.         0.53368726 0.72527046]
 [3.         3.    

In [33]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.53368726 0.72527046]
 [3.         3.         3.         0.         0.        ]
 [0.70483947 0.73413037 0.4718543  0.         0.        ]
 [0.95471388 0.40050119 0.19004815 0.60244919 0.86427857]
 [0.60667828 0.40264779 0.59155183 0.09964067 0.60965519]]

[[3.         3.         3.         0.53368726 0.72527046]
 [3.         3.         3.         0.         0.        ]
 [0.70483947 0.73413037 0.4718543  0.         0.        ]
 [0.95471388 0.40050119 0.19004815 0.60244919 0.86427857]
 [0.60667828 0.40264779 0.59155183 0.09964067 0.60965519]]
